// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrackHub.Manager.Domain.Models;
using TrackHub.Manager.Infrastructure;

#nullable disable

namespace TrackHub.Manager.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260705233432_MoveTelemetryTablesToTelemetrySchema")]
    partial class MoveTelemetryTablesToTelemetrySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("AccountId");

                    b.ToTable("accounts", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.AccountFeature", b =>
                {
                    b.Property<Guid>("AccountFeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("text")
                        .HasColumnName("configurationjson");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effectivefrom");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effectiveto");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("FeatureKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("featurekey");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tier");

                    b.HasKey("AccountFeatureId");

                    b.HasIndex("AccountId", "FeatureKey")
                        .IsUnique();

                    b.ToTable("account_features", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.AccountSettings", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Maps")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("maps");

                    b.Property<string>("MapsKey")
                        .HasColumnType("text")
                        .HasColumnName("mapskey");

                    b.Property<int>("OnlineInterval")
                        .HasColumnType("integer")
                        .HasColumnName("onlineinterval");

                    b.Property<bool>("RefreshMap")
                        .HasColumnType("boolean")
                        .HasColumnName("refreshmap");

                    b.Property<int>("RefreshMapInterval")
                        .HasColumnType("integer")
                        .HasColumnName("refreshmapinterval");

                    b.HasKey("AccountId");

                    b.ToTable("account_settings", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.AccountSupportGrant", b =>
                {
                    b.Property<Guid>("AccountSupportGrantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("accesslevel");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approvedat");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("approvedby");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("endsat");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revokedat");

                    b.Property<string>("RevokedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("revokedby");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startsat");

                    b.Property<Guid>("SupportUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("supportuserid");

                    b.Property<string>("TicketReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ticketreference");

                    b.HasKey("AccountSupportGrantId");

                    b.HasIndex("AccountId", "SupportUserId", "StartsAt", "EndsAt");

                    b.ToTable("account_support_grants", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.AlertEvent", b =>
                {
                    b.Property<Guid>("AlertEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeduplicationKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("deduplicationkey");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("eventtype");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("firstseenat");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastseenat");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("payloadjson");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("resourceid");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("resourcetype");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("severity");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("sourcemodule");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("status");

                    b.HasKey("AlertEventId");

                    b.HasIndex("DeduplicationKey");

                    b.HasIndex("AccountId", "Status", "LastSeenAt");

                    b.ToTable("alert_events", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("AuditEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("action");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actorid");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actortype");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlationid");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ipaddress");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("text")
                        .HasColumnName("newvaluesjson");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurredat");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("text")
                        .HasColumnName("oldvaluesjson");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("resourceid");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("resourcetype");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("result");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("useragent");

                    b.HasKey("AuditEventId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("AccountId", "OccurredAt");

                    b.ToTable("audit_events", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.BackgroundJobRun", b =>
                {
                    b.Property<Guid>("BackgroundJobRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completedat");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("errorcode");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("errormessage");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotencykey");

                    b.Property<string>("JobKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("jobkey");

                    b.Property<string>("ResourceKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("resourcekey");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startedat");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("status");

                    b.HasKey("BackgroundJobRunId");

                    b.HasIndex("AccountId", "StartedAt");

                    b.HasIndex("JobKey", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("background_job_runs", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Credential", b =>
                {
                    b.Property<Guid>("CredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("CredentialVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("credentialversion");

                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Key2")
                        .HasColumnType("text")
                        .HasColumnName("key2");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operatorid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refreshtoken");

                    b.Property<DateTimeOffset?>("RefreshTokenExpiration")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refreshtokenexpiration");

                    b.Property<DateTimeOffset?>("RotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rotatedat");

                    b.Property<string>("RotatedByPrincipalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rotatedbyprincipalid");

                    b.Property<string>("RotatedByPrincipalType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rotatedbyprincipaltype");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("salt");

                    b.Property<string>("Token")
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTimeOffset?>("TokenExpiration")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tokenexpiration");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uri");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("CredentialId");

                    b.HasIndex("OperatorId")
                        .IsUnique();

                    b.ToTable("credentials", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Device", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("DetectedStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("detectedstatus");

                    b.Property<short>("DeviceTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("devicetypeid");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("firstseenat");

                    b.Property<int>("Identifier")
                        .HasColumnType("integer")
                        .HasColumnName("identifier");

                    b.Property<DateTimeOffset?>("IgnoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ignoredat");

                    b.Property<DateTimeOffset?>("LastAssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastassignedat");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastseenat");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastsyncedat");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operatorid");

                    b.Property<string>("ProviderDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("providerdisplayname");

                    b.Property<string>("ProviderMetadataHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("providermetadatahash");

                    b.Property<string>("ProviderStatus")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("providerstatus");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial");

                    b.HasKey("DeviceId");

                    b.HasIndex("AccountId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("AccountId", "OperatorId", "Identifier")
                        .IsUnique();

                    b.HasIndex("AccountId", "OperatorId", "DetectedStatus", "LastSyncedAt");

                    b.ToTable("devices", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Document", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("classification");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contenttype");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiresat");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("OwnerEntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ownerentityid");

                    b.Property<string>("OwnerEntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ownerentitytype");

                    b.Property<string>("ScanStatus")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scanstatus");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("sha256hash");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("sizebytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storagekey");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("storageprovider");

                    b.Property<string>("UploadedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("uploadedbyprincipalid");

                    b.Property<string>("UploadedByPrincipalType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("uploadedbyprincipaltype");

                    b.Property<string>("VisibilityScope")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("visibilityscope");

                    b.HasKey("DocumentId");

                    b.HasIndex("Sha256Hash");

                    b.HasIndex("AccountId", "OwnerEntityType", "OwnerEntityId");

                    b.ToTable("documents", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Driver", b =>
                {
                    b.Property<Guid>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("DefaultTransporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("defaulttransporterid");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("documentnumber");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("documenttype");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("employeecode");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("LicenseExpiresAt")
                        .HasColumnType("date")
                        .HasColumnName("licenseexpiresat");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("licensenumber");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("phone");

                    b.HasKey("DriverId");

                    b.HasIndex("AccountId", "DocumentNumber");

                    b.ToTable("drivers", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.GeocodingProvider", b =>
                {
                    b.Property<Guid>("GeocodingProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("ApiKey")
                        .HasColumnType("text")
                        .HasColumnName("apikey");

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("text")
                        .HasColumnName("configurationjson");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("EndpointUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endpointuri");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("RequestsPerSecond")
                        .HasColumnType("integer")
                        .HasColumnName("requestspersecond");

                    b.Property<string>("Salt")
                        .HasColumnType("text")
                        .HasColumnName("salt");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timeoutseconds");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("GeocodingProviderId");

                    b.HasIndex("Active")
                        .IsUnique()
                        .HasDatabaseName("ix_geocoding_providers_single_active")
                        .HasFilter("active = true");

                    b.ToTable("geocoding_providers", "map");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Group", b =>
                {
                    b.Property<long>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GroupId"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("GroupId");

                    b.HasIndex("AccountId");

                    b.ToTable("groups", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.NotificationDelivery", b =>
                {
                    b.Property<Guid>("NotificationDeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<Guid?>("AlertEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("alerteventid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("NotificationRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("notificationruleid");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("providermessageid");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("readat");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("recipient");

                    b.Property<string>("RecipientPrincipalType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("recipientprincipaltype");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sentat");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("status");

                    b.HasKey("NotificationDeliveryId");

                    b.HasIndex("AccountId", "Status", "Channel");

                    b.ToTable("notification_deliveries", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.NotificationRule", b =>
                {
                    b.Property<Guid>("NotificationRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<string>("ChannelsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channelsjson");

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("text")
                        .HasColumnName("configurationjson");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("RecipientSelector")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipientselector");

                    b.Property<string>("RuleKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rulekey");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ruletype");

                    b.Property<string>("ThrottlingJson")
                        .HasColumnType("text")
                        .HasColumnName("throttlingjson");

                    b.Property<string>("TriggerEvent")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("triggerevent");

                    b.HasKey("NotificationRuleId");

                    b.HasIndex("AccountId", "RuleKey")
                        .IsUnique();

                    b.ToTable("notification_rules", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Operator", b =>
                {
                    b.Property<Guid>("OperatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("address");

                    b.Property<string>("ContactName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contactname");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("emailaddress");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<int>("HealthStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("healthstatus");

                    b.Property<DateTimeOffset?>("LastDeviceSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastdevicesyncat");

                    b.Property<DateTimeOffset?>("LastFailedSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastfailedsyncat");

                    b.Property<string>("LastFailureCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lastfailurecode");

                    b.Property<string>("LastFailureMessage")
                        .HasColumnType("text")
                        .HasColumnName("lastfailuremessage");

                    b.Property<int?>("LastLatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("lastlatencyms");

                    b.Property<DateTimeOffset?>("LastManualSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmanualsyncat");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastPositionSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastpositionsyncat");

                    b.Property<DateTimeOffset?>("LastSuccessfulSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastsuccessfulsyncat");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("phonenumber");

                    b.Property<int>("ProtocolType")
                        .HasColumnType("integer")
                        .HasColumnName("protocoltype");

                    b.Property<int>("SyncIntervalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60)
                        .HasColumnName("syncintervalminutes");

                    b.HasKey("OperatorId");

                    b.HasIndex("AccountId", "HealthStatus");

                    b.HasIndex("AccountId", "Enabled", "ProtocolType");

                    b.ToTable("operators", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.OperatorHealthCheck", b =>
                {
                    b.Property<Guid>("OperatorHealthCheckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<int>("CheckType")
                        .HasColumnType("integer")
                        .HasColumnName("checktype");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completedat");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlationid");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("errorcode");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("errormessage");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latencyms");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operatorid");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retrycount");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startedat");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("OperatorHealthCheckId");

                    b.HasIndex("AccountId", "OperatorId", "StartedAt");

                    b.ToTable("operator_health_checks", "telemetry");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.OperatorSyncRun", b =>
                {
                    b.Property<Guid>("OperatorSyncRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completedat");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlationid");

                    b.Property<int>("DevicesAdded")
                        .HasColumnType("integer")
                        .HasColumnName("devicesadded");

                    b.Property<int>("DevicesIgnored")
                        .HasColumnType("integer")
                        .HasColumnName("devicesignored");

                    b.Property<int>("DevicesRemoved")
                        .HasColumnType("integer")
                        .HasColumnName("devicesremoved");

                    b.Property<int>("DevicesSeen")
                        .HasColumnType("integer")
                        .HasColumnName("devicesseen");

                    b.Property<int>("DevicesUpdated")
                        .HasColumnType("integer")
                        .HasColumnName("devicesupdated");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("errorcode");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("errormessage");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operatorid");

                    b.Property<int>("PositionsAccepted")
                        .HasColumnType("integer")
                        .HasColumnName("positionsaccepted");

                    b.Property<int>("PositionsRead")
                        .HasColumnType("integer")
                        .HasColumnName("positionsread");

                    b.Property<int>("PositionsRejected")
                        .HasColumnType("integer")
                        .HasColumnName("positionsrejected");

                    b.Property<int>("Result")
                        .HasColumnType("integer")
                        .HasColumnName("result");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startedat");

                    b.Property<int>("TriggerType")
                        .HasColumnType("integer")
                        .HasColumnName("triggertype");

                    b.HasKey("OperatorSyncRunId");

                    b.HasIndex("AccountId", "StartedAt");

                    b.HasIndex("AccountId", "OperatorId", "StartedAt");

                    b.ToTable("operator_sync_runs", "telemetry");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.PointOfInterest", b =>
                {
                    b.Property<Guid>("PointOfInterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<short?>("Color")
                        .HasColumnType("smallint")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<long?>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("groupid");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("PointOfInterestId");

                    b.HasIndex("AccountId");

                    b.HasIndex("GroupId");

                    b.HasIndex("AccountId", "Active");

                    b.ToTable("points_of_interest", "map");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.PublicLinkGrant", b =>
                {
                    b.Property<Guid>("PublicLinkGrantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessCount")
                        .HasColumnType("integer")
                        .HasColumnName("accesscount");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("createdbyprincipalid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiresat");

                    b.Property<DateTimeOffset?>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastaccessedat");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("purpose");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("resourceid");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("resourcetype");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revokedat");

                    b.Property<string>("RevokedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("revokedby");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("scopes");

                    b.Property<string>("SubjectTokenIdHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subjecttokenidhash");

                    b.HasKey("PublicLinkGrantId");

                    b.HasIndex("SubjectTokenIdHash")
                        .IsUnique();

                    b.HasIndex("AccountId", "ResourceType", "ResourceId");

                    b.ToTable("public_link_grants", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Report", b =>
                {
                    b.Property<Guid>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("ReportId");

                    b.ToTable("reports", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Transporter", b =>
                {
                    b.Property<Guid>("TransporterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<short>("TransporterTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("transportertypeid");

                    b.HasKey("TransporterId");

                    b.HasIndex("AccountId");

                    b.HasIndex("TransporterTypeId");

                    b.ToTable("transporters", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.TransporterDeviceAssignment", b =>
                {
                    b.Property<Guid>("TransporterDeviceAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<string>("AssignmentReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("assignmentreason");

                    b.Property<string>("CreatedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("createdbyprincipalid");

                    b.Property<string>("CreatedByPrincipalType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("createdbyprincipaltype");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("deviceid");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effectivefrom");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effectiveto");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isprimary");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("priority");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<Guid>("TransporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("transporterid");

                    b.HasKey("TransporterDeviceAssignmentId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("TransporterId");

                    b.HasIndex("AccountId", "DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_transporter_device_assignments_active_device")
                        .HasFilter("status = 0");

                    b.HasIndex("AccountId", "DeviceId", "EffectiveFrom");

                    b.HasIndex("AccountId", "TransporterId", "EffectiveFrom");

                    b.ToTable("transporter_device_assignments", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.TransporterGroup", b =>
                {
                    b.Property<long>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("groupid");

                    b.Property<Guid>("TransporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("transporterid");

                    b.HasKey("GroupId", "TransporterId");

                    b.HasIndex("TransporterId");

                    b.ToTable("transporter_group", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.TransporterPosition", b =>
                {
                    b.Property<Guid>("TransporterPositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<double?>("Altitude")
                        .HasColumnType("double precision")
                        .HasColumnName("altitude");

                    b.Property<AttributesVm?>("Attributes")
                        .HasColumnType("json")
                        .HasColumnName("attributes");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<double?>("Course")
                        .HasColumnType("double precision")
                        .HasColumnName("course");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datetime");

                    b.Property<int?>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("eventId");

                    b.Property<Guid?>("GeometryId")
                        .HasColumnType("uuid")
                        .HasColumnName("geometryid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<TimeSpan>("Offset")
                        .HasColumnType("interval")
                        .HasColumnName("offset");

                    b.Property<double>("Speed")
                        .HasColumnType("double precision")
                        .HasColumnName("speed");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<Guid>("TransporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("transporterid");

                    b.HasKey("TransporterPositionId");

                    b.HasIndex("TransporterId")
                        .IsUnique();

                    b.ToTable("transporter_position", "telemetry");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.TransporterPositionHistory", b =>
                {
                    b.Property<Guid>("TransporterPositionHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("address");

                    b.Property<double?>("Altitude")
                        .HasColumnType("double precision")
                        .HasColumnName("altitude");

                    b.Property<string>("Attributes")
                        .HasColumnType("text")
                        .HasColumnName("attributes");

                    b.Property<string>("City")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("country");

                    b.Property<double?>("Course")
                        .HasColumnType("double precision")
                        .HasColumnName("course");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("deviceid");

                    b.Property<int?>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("eventid");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotencykey");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operatorid");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("receivedat");

                    b.Property<DateTimeOffset>("SourceTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sourcetimestamp");

                    b.Property<double>("Speed")
                        .HasColumnType("double precision")
                        .HasColumnName("speed");

                    b.Property<string>("State")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("state");

                    b.Property<Guid>("TransporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("transporterid");

                    b.HasKey("TransporterPositionHistoryId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("AccountId", "OperatorId", "SourceTimestamp");

                    b.HasIndex("AccountId", "TransporterId", "SourceTimestamp");

                    b.ToTable("transporter_position_history", "telemetry");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.TransporterType", b =>
                {
                    b.Property<short>("TransporterTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("TransporterTypeId"));

                    b.Property<bool>("AccBased")
                        .HasColumnType("boolean")
                        .HasColumnName("accbased");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<double>("MaxDistance")
                        .HasColumnType("double precision")
                        .HasColumnName("maxdistance");

                    b.Property<double>("MaxTimeGap")
                        .HasColumnType("double precision")
                        .HasColumnName("maxtimegap");

                    b.Property<double>("StoppedGap")
                        .HasColumnType("double precision")
                        .HasColumnName("stoppedgap");

                    b.HasKey("TransporterTypeId");

                    b.ToTable("transporter_type", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("AccountId", "Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_accountid_username");

                    b.ToTable("users", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.UserGroup", b =>
                {
                    b.Property<long>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("groupid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("user_group", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.UserSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("Navbar")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("navbar");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("style");

                    b.HasKey("UserId");

                    b.ToTable("user_settings", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.AccountFeature", b =>
                {
                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.Account", null)
                        .WithMany("AccountFeatures")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.AccountSettings", b =>
                {
                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.Account", "Account")
                        .WithOne("AccountSettings")
                        .HasForeignKey("TrackHub.Manager.Infrastructure.Entities.AccountSettings", "AccountId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Credential", b =>
                {
                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.Operator", "Operator")
                        .WithOne("Credential")
                        .HasForeignKey("TrackHub.Manager.Infrastructure.Entities.Credential", "OperatorId");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Device", b =>
                {
                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.Account", "Account")
                        .WithMany("Devices")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.Operator", "Operator")
                        .WithMany("Devices")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Driver", b =>
                {
                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.Account", null)
                        .WithMany("Drivers")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Group", b =>
                {
                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.Account", "Account")
                        .WithMany("Groups")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Operator", b =>
                {
                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.Account", "Account")
                        .WithMany("Operators")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.PointOfInterest", b =>
                {
                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.Navigation("Account");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Transporter", b =>
                {
                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.Account", "Account")
                        .WithMany("Transporters")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.TransporterType", "TransporterType")
                        .WithMany()
                        .HasForeignKey("TransporterTypeId");

                    b.Navigation("Account");

                    b.Navigation("TransporterType");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.TransporterDeviceAssignment", b =>
                {
                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.Device", "Device")
                        .WithMany("Assignments")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.Transporter", "Transporter")
                        .WithMany("Assignments")
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Transporter");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.TransporterGroup", b =>
                {
                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.Transporter", "Transporter")
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Transporter");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.TransporterPosition", b =>
                {
                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.Transporter", "Transporter")
                        .WithOne("Position")
                        .HasForeignKey("TrackHub.Manager.Infrastructure.Entities.TransporterPosition", "TransporterId");

                    b.Navigation("Transporter");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.User", b =>
                {
                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.Account", "Account")
                        .WithMany("Users")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.UserGroup", b =>
                {
                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.UserSettings", b =>
                {
                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.User", "User")
                        .WithOne("UserSettings")
                        .HasForeignKey("TrackHub.Manager.Infrastructure.Entities.UserSettings", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Account", b =>
                {
                    b.Navigation("AccountFeatures");

                    b.Navigation("AccountSettings");

                    b.Navigation("Devices");

                    b.Navigation("Drivers");

                    b.Navigation("Groups");

                    b.Navigation("Operators");

                    b.Navigation("Transporters");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Device", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Operator", b =>
                {
                    b.Navigation("Credential");

                    b.Navigation("Devices");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Transporter", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.User", b =>
                {
                    b.Navigation("UserSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
