// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrackHub.Manager.Domain.Models;
using TrackHub.Manager.Infrastructure;

#nullable disable

namespace TrackHub.Manager.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260121022010_AddSettings")]
    partial class AddSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("AccountId");

                    b.ToTable("accounts", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.AccountSettings", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("EnableGeofencing")
                        .HasColumnType("boolean")
                        .HasColumnName("geofencing");

                    b.Property<bool>("EnableTripManagement")
                        .HasColumnType("boolean")
                        .HasColumnName("tripmanagement");

                    b.Property<string>("Maps")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("maps");

                    b.Property<string>("MapsKey")
                        .HasColumnType("text")
                        .HasColumnName("mapskey");

                    b.Property<int>("OnlineInterval")
                        .HasColumnType("integer")
                        .HasColumnName("onlineinterval");

                    b.Property<bool>("RefreshMap")
                        .HasColumnType("boolean")
                        .HasColumnName("refreshmap");

                    b.Property<int>("RefreshMapInterval")
                        .HasColumnType("integer")
                        .HasColumnName("refreshmapinterval");

                    b.Property<bool>("StoreLastPosition")
                        .HasColumnType("boolean")
                        .HasColumnName("storelastposition");

                    b.Property<int>("StoringInterval")
                        .HasColumnType("integer")
                        .HasColumnName("storinginterval");

                    b.HasKey("AccountId");

                    b.ToTable("account_settings", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Credential", b =>
                {
                    b.Property<Guid>("CredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Key2")
                        .HasColumnType("text")
                        .HasColumnName("key2");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operatorid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refreshtoken");

                    b.Property<DateTimeOffset?>("RefreshTokenExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("salt");

                    b.Property<string>("Token")
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTimeOffset?>("TokenExpiration")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tokenexpiration");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uri");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("CredentialId");

                    b.HasIndex("OperatorId")
                        .IsUnique();

                    b.ToTable("credentials", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Device", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<short>("DeviceTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("devicetypeid");

                    b.Property<int>("Identifier")
                        .HasMaxLength(100)
                        .HasColumnType("integer")
                        .HasColumnName("identifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operatorid");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial");

                    b.Property<Guid?>("TransporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("transporterid");

                    b.HasKey("DeviceId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("TransporterId");

                    b.ToTable("devices", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Group", b =>
                {
                    b.Property<long>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GroupId"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("GroupId");

                    b.HasIndex("AccountId");

                    b.ToTable("groups", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Operator", b =>
                {
                    b.Property<Guid>("OperatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("address");

                    b.Property<string>("ContactName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contactname");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("emailaddress");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("phonenumber");

                    b.Property<int>("ProtocolType")
                        .HasColumnType("integer")
                        .HasColumnName("protocoltype");

                    b.HasKey("OperatorId");

                    b.HasIndex("AccountId");

                    b.ToTable("operators", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Report", b =>
                {
                    b.Property<Guid>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("ReportId");

                    b.ToTable("reports", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Transporter", b =>
                {
                    b.Property<Guid>("TransporterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<short>("TransporterTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("transportertypeid");

                    b.HasKey("TransporterId");

                    b.HasIndex("TransporterTypeId");

                    b.ToTable("transporters", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.TransporterGroup", b =>
                {
                    b.Property<long>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("groupid");

                    b.Property<Guid>("TransporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("transporterid");

                    b.HasKey("GroupId", "TransporterId");

                    b.HasIndex("TransporterId");

                    b.ToTable("transporter_group", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.TransporterPosition", b =>
                {
                    b.Property<Guid>("TransporterPositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<double?>("Altitude")
                        .HasColumnType("double precision")
                        .HasColumnName("altitude");

                    b.Property<AttributesVm?>("Attributes")
                        .HasColumnType("json")
                        .HasColumnName("attributes");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<double?>("Course")
                        .HasColumnType("double precision")
                        .HasColumnName("course");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datetime");

                    b.Property<int?>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("eventId");

                    b.Property<Guid?>("GeometryId")
                        .HasColumnType("uuid")
                        .HasColumnName("geometryid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<TimeSpan>("Offset")
                        .HasColumnType("interval")
                        .HasColumnName("offset");

                    b.Property<double>("Speed")
                        .HasColumnType("double precision")
                        .HasColumnName("speed");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<Guid>("TransporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("transporterid");

                    b.HasKey("TransporterPositionId");

                    b.HasIndex("TransporterId")
                        .IsUnique();

                    b.ToTable("transporter_position", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.TransporterType", b =>
                {
                    b.Property<short>("TransporterTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("TransporterTypeId"));

                    b.Property<bool>("AccBased")
                        .HasColumnType("boolean")
                        .HasColumnName("accbased");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<double>("MaxDistance")
                        .HasColumnType("double precision")
                        .HasColumnName("maxdistance");

                    b.Property<double>("MaxTimeGap")
                        .HasColumnType("double precision")
                        .HasColumnName("maxtimegap");

                    b.Property<double>("StoppedGap")
                        .HasColumnType("double precision")
                        .HasColumnName("stoppedgap");

                    b.HasKey("TransporterTypeId");

                    b.ToTable("transporter_type", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("AccountId");

                    b.ToTable("users", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.UserGroup", b =>
                {
                    b.Property<long>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("groupid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("user_group", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.UserSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("Navbar")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("navbar");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("style");

                    b.HasKey("UserId");

                    b.ToTable("user_settings", "app");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.AccountSettings", b =>
                {
                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.Account", "Account")
                        .WithOne("AccountSettings")
                        .HasForeignKey("TrackHub.Manager.Infrastructure.Entities.AccountSettings", "AccountId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Credential", b =>
                {
                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.Operator", "Operator")
                        .WithOne("Credential")
                        .HasForeignKey("TrackHub.Manager.Infrastructure.Entities.Credential", "OperatorId");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Device", b =>
                {
                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.Operator", "Operator")
                        .WithMany("Devices")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.Transporter", "Transporter")
                        .WithMany("Devices")
                        .HasForeignKey("TransporterId");

                    b.Navigation("Operator");

                    b.Navigation("Transporter");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Group", b =>
                {
                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.Account", "Account")
                        .WithMany("Groups")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Operator", b =>
                {
                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.Account", "Account")
                        .WithMany("Operators")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Transporter", b =>
                {
                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.TransporterType", "TransporterType")
                        .WithMany()
                        .HasForeignKey("TransporterTypeId");

                    b.Navigation("TransporterType");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.TransporterGroup", b =>
                {
                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.Transporter", "Transporter")
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Transporter");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.TransporterPosition", b =>
                {
                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.Transporter", "Transporter")
                        .WithOne("Position")
                        .HasForeignKey("TrackHub.Manager.Infrastructure.Entities.TransporterPosition", "TransporterId");

                    b.Navigation("Transporter");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.User", b =>
                {
                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.Account", "Account")
                        .WithMany("Users")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.UserGroup", b =>
                {
                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.UserSettings", b =>
                {
                    b.HasOne("TrackHub.Manager.Infrastructure.Entities.User", "User")
                        .WithOne("UserSettings")
                        .HasForeignKey("TrackHub.Manager.Infrastructure.Entities.UserSettings", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Account", b =>
                {
                    b.Navigation("AccountSettings");

                    b.Navigation("Groups");

                    b.Navigation("Operators");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Operator", b =>
                {
                    b.Navigation("Credential");

                    b.Navigation("Devices");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.Transporter", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.Entities.User", b =>
                {
                    b.Navigation("UserSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
